#!/bin/bash
#PBS -l nodes=8:ppn=16
#PBS -l walltime=120:00:00
#PBS -N sb6i7
#PBS -m bae
#PBS -M xinlei.liu@seh.ox.ac.uk


module load espresso/5.3.0

# develq - short queue with walltime 10 minutes and maximum 2 nodes
# to submit to develq: qsub -q develq script.pbs

# Set up mpi on ARCUS
. enable_arcus_mpi.sh


# Executable aliases
export MPI_GROUP_MAX=64


# Copy to TMPDIR all files required for start
cd $PBS_O_WORKDIR

mpirun $MPI_HOSTS pw.x -npool 8 < sb6i7-relax.in > sb6i7-relax-PBE2.out

